import { Injectable, signal } from '@angular/core';

export type Lang = 'uz' | 'ru' | 'en';

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  uz: {
    APP_TITLE: "Oila Daraxti",
    HERO_SUBTITLE: "Oila tarixi, avlodlar va xotiralar",
    NAV_HOME: "Bosh sahifa",
    NAV_NOTIFICATIONS: "Bildirishnomalar",
    SEARCH_PLACEHOLDER: "Oila a'zosini izlang...",
    GENERATION: "Avlod",
    BORN: "Tug'ilgan",
    DIED: "Vafot etgan",
    SPOUSE: "Turmush o'rtog'i",
    CHILDREN: "Farzandlar",
    PARENTS: "Ota-ona",
    FATHER: "Otasi",
    MOTHER: "Onasi",
    ABOUT: "Haqida",
    GALLERY: "Galereya",
    VIDEOS: "Videolar",
    PHONE: "Telefon",
    EMAIL: "Email",
    YEARS_OLD: "yosh",
    YEARS_OF_LIFE: "yil umr ko'rdi",
    ADMIN_LOGIN: "Admin panelga kirish",
    USERNAME: "Foydalanuvchi nomi",
    PASSWORD: "Parol",
    LOGIN: "Kirish",
    ADD_MEMBER: "A'zo qo'shish",
    EDIT_MEMBER: "A'zoni tahrirlash",
    SAVE: "Saqlash",
    CANCEL: "Bekor qilish",
    NAME_UZ: "Ismi (O'zbekcha)",
    NAME_RU: "Ismi (Ruscha)",
    NAME_EN: "Ismi (Inglizcha)",
    BIRTH_DATE: "Tug'ilgan sana",
    DEATH_DATE: "Vafot etgan sana",
    GENDER: "Jins",
    MALE: "Erkak",
    FEMALE: "Ayol",
    GENERATION_NUM: "Avlod raqami",
    SPOUSE_FIELD: "Turmush o'rtog'i",
    PHOTO: "Rasm",
    BIO_UZ: "Tarjimai hol (O'zbekcha)",
    BIO_RU: "Tarjimai hol (Ruscha)",
    BIO_EN: "Tarjimai hol (Inglizcha)",
    UPLOAD_PHOTO: "Rasm yuklash",
    UPLOAD_MEDIA: "Rasm/Video qo'shish",
    TOTAL_MEMBERS: "Jami a'zolar",
    TODAY_BIRTHDAYS: "Bugungi tug'ilgan kunlar",
    UPCOMING_BIRTHDAYS: "Yaqinlashayotgan tug'ilgan kunlar",
    DAYS_LEFT: "kun qoldi",
    ALL_GEN: "Barchasi",
    TREE_VIEW: "Shajara",
    LIST_VIEW: "Ro'yxat",
    MARK_READ: "O'qilgan deb belgilash",
    MARK_ALL_READ: "Hammasini o'qilgan deb belgilash",
    NO_NOTIFICATIONS: "Bildirishnomalar yo'q",
    NOTIF_HINT: "Tug'ilgan kunlar yaqinlashganda bu yerda ko'rinadi",
    BIRTHDAY_TODAY: "Bugun tug'ilgan kun!",
    FAMILY_CONNECTIONS: "Oila aloqalari",
    COPY_LINK: "Havolani nusxalash",
    LINK_COPIED: "Nusxalandi!",
    BACK: "Orqaga",
    LOADING: "Yuklanmoqda...",
    NO_DATA: "Ma'lumot yo'q",
    ERROR: "Xatolik yuz berdi",
    SUCCESS: "Muvaffaqiyatli saqlandi",
    SELECT_FATHER: "Otasini tanlang",
    SELECT_MOTHER: "Onasini tanlang",
    SELECT_SPOUSE: "Turmush o'rtog'ini tanlang",
    ALIVE: "Hayot",
    DECEASED: "Vafot etgan",
    MALE_COUNT: "Erkaklar",
    FEMALE_COUNT: "Ayollar",
    GEN_COUNT: "Avlodlar",
  },
  ru: {
    APP_TITLE: "Семейное Древо",
    HERO_SUBTITLE: "История семьи, поколения и воспоминания",
    NAV_HOME: "Главная",
    NAV_NOTIFICATIONS: "Уведомления",
    SEARCH_PLACEHOLDER: "Поиск члена семьи...",
    GENERATION: "Поколение",
    BORN: "Дата рождения",
    DIED: "Дата смерти",
    SPOUSE: "Супруг/Супруга",
    CHILDREN: "Дети",
    PARENTS: "Родители",
    FATHER: "Отец",
    MOTHER: "Мать",
    ABOUT: "О человеке",
    GALLERY: "Галерея",
    VIDEOS: "Видео",
    PHONE: "Телефон",
    EMAIL: "Email",
    YEARS_OLD: "лет",
    YEARS_OF_LIFE: "лет жизни",
    ADMIN_LOGIN: "Вход в панель администратора",
    USERNAME: "Имя пользователя",
    PASSWORD: "Пароль",
    LOGIN: "Войти",
    ADD_MEMBER: "Добавить члена",
    EDIT_MEMBER: "Редактировать",
    SAVE: "Сохранить",
    CANCEL: "Отмена",
    NAME_UZ: "Имя (Узбекский)",
    NAME_RU: "Имя (Русский)",
    NAME_EN: "Имя (Английский)",
    BIRTH_DATE: "Дата рождения",
    DEATH_DATE: "Дата смерти",
    GENDER: "Пол",
    MALE: "Мужской",
    FEMALE: "Женский",
    GENERATION_NUM: "Номер поколения",
    SPOUSE_FIELD: "Супруг/Супруга",
    PHOTO: "Фото",
    BIO_UZ: "Биография (Узбекский)",
    BIO_RU: "Биография (Русский)",
    BIO_EN: "Биография (Английский)",
    UPLOAD_PHOTO: "Загрузить фото",
    UPLOAD_MEDIA: "Добавить фото/видео",
    TOTAL_MEMBERS: "Всего членов",
    TODAY_BIRTHDAYS: "Дни рождения сегодня",
    UPCOMING_BIRTHDAYS: "Предстоящие дни рождения",
    DAYS_LEFT: "дней осталось",
    ALL_GEN: "Все",
    TREE_VIEW: "Дерево",
    LIST_VIEW: "Список",
    MARK_READ: "Отметить прочитанным",
    MARK_ALL_READ: "Отметить все прочитанными",
    NO_NOTIFICATIONS: "Нет уведомлений",
    NOTIF_HINT: "Здесь будут отображаться напоминания о днях рождения",
    BIRTHDAY_TODAY: "Сегодня день рождения!",
    FAMILY_CONNECTIONS: "Семейные связи",
    COPY_LINK: "Скопировать ссылку",
    LINK_COPIED: "Скопировано!",
    BACK: "Назад",
    LOADING: "Загрузка...",
    NO_DATA: "Нет данных",
    ERROR: "Произошла ошибка",
    SUCCESS: "Успешно сохранено",
    SELECT_FATHER: "Выберите отца",
    SELECT_MOTHER: "Выберите мать",
    SELECT_SPOUSE: "Выберите супруга/супругу",
    ALIVE: "Живой/Живая",
    DECEASED: "Умер/Умерла",
    MALE_COUNT: "Мужчины",
    FEMALE_COUNT: "Женщины",
    GEN_COUNT: "Поколений",
  },
  en: {
    APP_TITLE: "Family Tree",
    HERO_SUBTITLE: "Family history, generations and memories",
    NAV_HOME: "Home",
    NAV_NOTIFICATIONS: "Notifications",
    SEARCH_PLACEHOLDER: "Search family member...",
    GENERATION: "Generation",
    BORN: "Born",
    DIED: "Died",
    SPOUSE: "Spouse",
    CHILDREN: "Children",
    PARENTS: "Parents",
    FATHER: "Father",
    MOTHER: "Mother",
    ABOUT: "About",
    GALLERY: "Gallery",
    VIDEOS: "Videos",
    PHONE: "Phone",
    EMAIL: "Email",
    YEARS_OLD: "years old",
    YEARS_OF_LIFE: "years of life",
    ADMIN_LOGIN: "Admin Panel Login",
    USERNAME: "Username",
    PASSWORD: "Password",
    LOGIN: "Login",
    ADD_MEMBER: "Add Member",
    EDIT_MEMBER: "Edit Member",
    SAVE: "Save",
    CANCEL: "Cancel",
    NAME_UZ: "Name (Uzbek)",
    NAME_RU: "Name (Russian)",
    NAME_EN: "Name (English)",
    BIRTH_DATE: "Birth Date",
    DEATH_DATE: "Death Date",
    GENDER: "Gender",
    MALE: "Male",
    FEMALE: "Female",
    GENERATION_NUM: "Generation Number",
    SPOUSE_FIELD: "Spouse",
    PHOTO: "Photo",
    BIO_UZ: "Biography (Uzbek)",
    BIO_RU: "Biography (Russian)",
    BIO_EN: "Biography (English)",
    UPLOAD_PHOTO: "Upload Photo",
    UPLOAD_MEDIA: "Add Photo/Video",
    TOTAL_MEMBERS: "Total Members",
    TODAY_BIRTHDAYS: "Today's Birthdays",
    UPCOMING_BIRTHDAYS: "Upcoming Birthdays",
    DAYS_LEFT: "days left",
    ALL_GEN: "All",
    TREE_VIEW: "Tree",
    LIST_VIEW: "List",
    MARK_READ: "Mark as Read",
    MARK_ALL_READ: "Mark All as Read",
    NO_NOTIFICATIONS: "No notifications",
    NOTIF_HINT: "Birthday reminders will appear here",
    BIRTHDAY_TODAY: "Birthday Today!",
    FAMILY_CONNECTIONS: "Family Connections",
    COPY_LINK: "Copy Link",
    LINK_COPIED: "Copied!",
    BACK: "Back",
    LOADING: "Loading...",
    NO_DATA: "No data",
    ERROR: "An error occurred",
    SUCCESS: "Successfully saved",
    SELECT_FATHER: "Select father",
    SELECT_MOTHER: "Select mother",
    SELECT_SPOUSE: "Select spouse",
    ALIVE: "Alive",
    DECEASED: "Deceased",
    MALE_COUNT: "Males",
    FEMALE_COUNT: "Females",
    GEN_COUNT: "Generations",
  },
};

@Injectable({ providedIn: 'root' })
export class TranslateService {
  private data = signal<Record<string, string>>(TRANSLATIONS.uz);
  currentLang = signal<Lang>('uz');

  constructor() {
    const saved = (localStorage.getItem('lang') as Lang) || 'uz';
    this.load(saved);
  }

  load(lang: Lang): void {
    this.data.set(TRANSLATIONS[lang] || TRANSLATIONS.uz);
    this.currentLang.set(lang);
    localStorage.setItem('lang', lang);
  }

  t(key: string): string {
    return this.data()[key] || key;
  }

  getName(item: any): string {
    if (!item) return '';
    const lang = this.currentLang();
    return item[`name_${lang}`] || item.name_uz || '';
  }

  getBio(item: any): string {
    if (!item) return '';
    const lang = this.currentLang();
    return item[`bio_${lang}`] || item.bio_uz || '';
  }

  getMessage(item: any): string {
    if (!item) return '';
    const lang = this.currentLang();
    return item[`message_${lang}`] || item.message_uz || '';
  }
}
